from typing import List, Optional
from uuid import uuid4
import os

from fastapi import FastAPI, HTTPException
from pydantic import BaseModel


class AnalyzeRequest(BaseModel):
    """Incoming payload for starting a drill analysis job.

    This is intentionally generic and does NOT expose any
    proprietary internal schema details.
    """

    drill_type: str
    cadet_id: Optional[str] = None
    video_url: Optional[str] = None
    # Optional metadata fields a real client might send
    metadata: Optional[dict] = None


class FeedbackItem(BaseModel):
    """Single feedback item returned to the client."""

    timestamp: float
    message: str
    severity: str


class AnalyzeResponse(BaseModel):
    """High-level response for an analysis request.

    In a real system this would likely be asynchronous and
    return just a job_id, with detailed feedback fetched
    from a separate endpoint once processing completes.
    """

    job_id: str
    status: str
    overall_score: Optional[float] = None
    feedback: List[FeedbackItem] = []


class HealthResponse(BaseModel):
    """Health check response schema."""

    status: str
    service: str
    environment: str


app = FastAPI(
    title="DrillSight Technical Showcase API",
    description=(
        "Public-facing API shell used to demonstrate the "
        "production architecture around DrillSight without "
        "exposing proprietary ML models or drill logic."
    ),
    version="0.1.0",
)


@app.get("/health", response_model=HealthResponse, tags=["meta"])
async def health() -> HealthResponse:
    """Lightweight health endpoint used by containers and load balancers.

    In a production deployment, this could also:
    - Ping the Redis cache.
    - Check connectivity to the primary database.
    - Optionally validate that the ML inference service is reachable.
    """

    env = os.getenv("DRILLSIGHT_ENV", "unknown")

    # NOTE: Intentionally not calling any real external services here
    # so that the container runs out-of-the-box in any environment.

    return HealthResponse(status="ok", service="drillsight-api", environment=env)


@app.post("/analyze", response_model=AnalyzeResponse, tags=["analysis"])
async def analyze(payload: AnalyzeRequest) -> AnalyzeResponse:
    """Start a drill analysis request.

    This is a MOCK implementation intended only for the
    technical showcase. It demonstrates the contract and
    where the proprietary ML pipeline would plug in.

    Proprietary ML Logic Integration Point (conceptual steps):
    1. Validate and persist the incoming request & metadata.
    2. Fetch the video (from `video_url` or an upload bucket).
    3. Run the DrillSight CV pipeline (pose estimation, drill analyzers).
    4. Store metrics, per-frame feedback, and aggregate scores.
    5. Return a `job_id` so clients can query detailed results.
    """

    if not payload.video_url:
        # In a real deployment you would likely accept uploads
        # via a separate endpoint or pre-signed URLs.
        raise HTTPException(status_code=400, detail="video_url is required in this mock implementation")

    job_id = str(uuid4())

    # In the real system, the job would be queued for background
    # processing and this response would likely contain only the
    # job identifier and initial status.

    mock_feedback = [
        FeedbackItem(
            timestamp=12.4,
            message="Mock feedback: Proprietary ML logic would annotate this event.",
            severity="info",
        )
    ]

    return AnalyzeResponse(
        job_id=job_id,
        status="queued",
        overall_score=None,
        feedback=mock_feedback,
    )


@app.get("/feedback/{job_id}", response_model=AnalyzeResponse, tags=["analysis"])
async def get_feedback(job_id: str) -> AnalyzeResponse:
    """Retrieve feedback for a previously submitted analysis job.

    This endpoint is a stub that returns deterministic mock data.
    In a production system, this would:
    - Look up the job in a database or cache.
    - Return the persisted metrics and feedback generated by the
      proprietary DrillSight analysis pipeline.
    """

    # Proprietary ML Logic Integration Point:
    # Replace this with a lookup in your job store / DB.

    mock_feedback = [
        FeedbackItem(
            timestamp=10.0,
            message="Mock feedback for job {job_id}: replace with real analysis output.",
            severity="info",
        )
    ]

    return AnalyzeResponse(
        job_id=job_id,
        status="completed",
        overall_score=85.0,
        feedback=mock_feedback,
    )
